# Describes the format for available Anycubic Cloud services

multi_color_box_set_slot_pla: &multi_color_box_set_slot
  fields:
    config_entry: &anycubic_config_entry
      required: true
      selector:
        config_entry:
          integration: anycubic_cloud
    printer_id: &printer_id
      required: true
      selector:
        number:
          min: 0
          max: 9999999999999999999
          step: 1
          mode: box
    box_id: &box_id
      required: false
      selector:
        number:
          min: 0
          max: 7
          step: 1
          mode: box
    slot_number: &slot_number
      required: true
      selector:
        number:
          min: 1
          max: 4
          step: 1
          mode: box
    slot_color_red:
      required: true
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: box
    slot_color_green:
      required: true
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: box
    slot_color_blue:
      required: true
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: box
multi_color_box_set_slot_petg: *multi_color_box_set_slot
multi_color_box_set_slot_abs: *multi_color_box_set_slot
multi_color_box_set_slot_pacf: *multi_color_box_set_slot
multi_color_box_set_slot_pc: *multi_color_box_set_slot
multi_color_box_set_slot_asa: *multi_color_box_set_slot
multi_color_box_set_slot_hips: *multi_color_box_set_slot
multi_color_box_set_slot_pa: *multi_color_box_set_slot
multi_color_box_set_slot_pla_se: *multi_color_box_set_slot
multi_color_box_filament_extrude:
  fields:
    config_entry: *anycubic_config_entry
    printer_id: *printer_id
    box_id: *box_id
    slot_number: *slot_number
    finished:
      required: false
      selector:
        boolean:
multi_color_box_filament_retract:
  fields:
    config_entry: *anycubic_config_entry
    printer_id: *printer_id
    box_id: *box_id
